### ISSUE TITLE
`setup.py` depends on `py2exe`

### ISSUE THREAD

**Issue by michaelmhoffman** [TarasKuzyo/LaTeXpkges#14]
If installing on Unix, there is no need for `py2exe` so this shouldn't be a hard requirement.

```
$ pip install git+https://github.com/TarasKuzyo/LaTeXpkges.git
Collecting git+https://github.com/TarasKuzyo/LaTeXpkges.git
  Cloning https://github.com/TarasKuzyo/LaTeXpkges.git to /tmp/pip-req-build-4ekiv_l3
  Running command git clone -q https://github.com/TarasKuzyo/LaTeXpkges.git /tmp/pip-req-build-4ekiv_l3
    ERROR: Command errored out with exit status 1:
     command: /home/mhoffman/venv/python3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4ekiv_l3/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4ekiv_l3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-4ekiv_l3/pip-egg-info
         cwd: /tmp/pip-req-build-4ekiv_l3/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4ekiv_l3/setup.py", line 2, in <module>
        import py2exe
    ImportError: No module named 'py2exe'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by TarasKuzyo** [comment]
Already resolved
